# Generated by Django 6.0.3 on 2026-04-04 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('HUEVOS', 'Huevos y Derivados'), ('POLLO', 'Pollo y Carnes Blancas'), ('VEG', 'Vegetales y Frutas'), ('LACTEOS', 'Lácteos y Derivados')], default='HUEVOS', max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('es_organico', models.BooleanField(default=False, verbose_name='¿Es orgánico?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='VariacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(help_text='Ej: Bloque 500g, Bolsa 1 Litro, Atado Pequeño', max_length=50)),
                ('unidad_medida', models.CharField(choices=[('UN', 'Unidad'), ('LT', 'Litro'), ('KG', 'Kilogramo'), ('LB', 'Libra'), ('AT', 'Atado'), ('CB', 'Cubeta(30 unds)')], default='UN', max_length=2)),
                ('precio', models.PositiveIntegerField(verbose_name='Precio de venta (COP)')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaciones', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Variación de Producto',
                'verbose_name_plural': 'Variaciones de Productos',
            },
        ),
    ]
