# Generated by Django 6.0.3 on 2026-04-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
        ('productos', '0002_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produccionhuevos',
            options={'verbose_name': 'Producción de Huevo', 'verbose_name_plural': 'Producción de Huevos'},
        ),
        migrations.AddField(
            model_name='produccionhuevos',
            name='variacion_objetivo',
            field=models.ForeignKey(blank=True, help_text='Seleccione qué producto del catálogo recibirá este stock', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.variacionproducto', verbose_name='Producto/Presentación en Tienda'),
        ),
        migrations.AlterField(
            model_name='produccionhuevos',
            name='cantidad_total',
            field=models.PositiveIntegerField(verbose_name='Cantidad (Unidades)'),
        ),
        migrations.AlterField(
            model_name='produccionhuevos',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recolecciones', to='produccion.loteaves', verbose_name='Lote de Aves'),
        ),
    ]
