# Generated by Django 6.0.3 on 2026-04-04 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmovimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockagricola',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.productoagricola'),
        ),
        migrations.AddField(
            model_name='stockhuevo',
            name='produccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produccion.produccionhuevos'),
        ),
    ]
