# Generated by Django 6.0.3 on 2026-04-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('HUEVOS', 'Huevos y Derivados'), ('POLLO', 'Pollo y Carnes Blancas'), ('VEG', 'Vegetales y Frutas'), ('LACTEOS', 'Lácteos y Derivados'), ('TUBERCULOS', 'Tubérculos'), ('GRANOS', 'Granos y Harinas')], default='HUEVOS', max_length=10),
        ),
        migrations.AlterField(
            model_name='variacionproducto',
            name='unidad_medida',
            field=models.CharField(choices=[('UN', 'Unidad'), ('LT', 'Litro'), ('KG', 'Kilogramo'), ('LB', 'Libra'), ('AT', 'Atado'), ('CB', 'Cubeta(30 unds)'), ('CN', 'Canasta'), ('PQ', 'Paquete'), ('ML', 'Mililitro'), ('G', 'Gramos')], default='UN', max_length=2),
        ),
    ]
