# Generated by Django 6.0.3 on 2026-04-19 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_alter_produccionhuevos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteaves',
            name='cantidad_inicial',
            field=models.PositiveIntegerField(verbose_name='Pollos recibidos'),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='codigo_lote',
            field=models.CharField(help_text='Ej: LOTE-2026-001', max_length=20),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Lote Activo'),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='mortalidad_acumulada',
            field=models.PositiveIntegerField(default=0, help_text='Total de aves muertas a la fecha'),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='raza',
            field=models.CharField(choices=[('ROSS', 'Ross 308 (Carne)'), ('COBB', 'Cobb 500 (Carne)'), ('ISA', 'Isa Brown (Ponedora)'), ('HYL', 'Hy-Line (Ponedora)'), ('OTRA', 'Otra Raza')], default='ROSS', max_length=50),
        ),
    ]
