# Generated by Django 6.0.3 on 2026-04-04 07:15

import django.db.models.deletion
import django.utils.timezone
import produccion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoteAves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('cantidad_inicial', models.PositiveIntegerField()),
                ('raza', models.CharField(max_length=50)),
                ('mortalidad_acumulada', models.PositiveIntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='lotes/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('fecha_siembra', models.DateField(validators=[produccion.models.validar_fecha_no_pasada])),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionHuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recoleccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_total', models.PositiveIntegerField()),
                ('clasificacion', models.CharField(choices=[('AAA', 'Triple A'), ('AA', 'Doble A'), ('A', 'A'), ('B', 'B')], max_length=5)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recolecciones', to='produccion.loteaves')),
            ],
        ),
    ]
